services:
  bussiness-service:
    build: ./services/businesses-4002
    container_name: bussiness-service
    ports:
      - "4002:4002"
    environment:
      - MONGODB=${MONGODB}
      - NODE_ENV=production

  users-and-payment-service:
    build: ./services/usersAndPayment-4001
    container_name: users-and-payment-service
    ports:
      - "4001:4001"
    environment:
      - MONGODB=${MONGODB}
      - NODE_ENV=production

  orchestrator:
    build: ./orchestrator-express
    container_name: orchestrator
    ports:
      - "80:4000"
    environment:
      - REDIS_URL=${REDIS_URL}
      - BUSSINESS_URL=http://bussiness-service:4002
      - USER_URL=http://users-and-payment-service:4001
